// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDlWgzw-q8Nchpu29bdMZr-QrmHO2fZE4',
    appId: '1:446244769194:web:5cb097aebb02a31cf0efd3',
    messagingSenderId: '446244769194',
    projectId: 'charlotte-substrate',
    authDomain: 'charlotte-substrate.firebaseapp.com',
    storageBucket: 'charlotte-substrate.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcuQf466lK-pPuvUO4mKk8HalEyL6Jw1Q',
    appId: '1:446244769194:android:004cc42c9c0236cbf0efd3',
    messagingSenderId: '446244769194',
    projectId: 'charlotte-substrate',
    storageBucket: 'charlotte-substrate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATJkrTc7d2WiYlhsj9vb6H4IKeq4JAyf8',
    appId: '1:446244769194:ios:ea9262eeafc0d43bf0efd3',
    messagingSenderId: '446244769194',
    projectId: 'charlotte-substrate',
    storageBucket: 'charlotte-substrate.firebasestorage.app',
    iosBundleId: 'com.charlotte.charlotte',
  );
}
