// GENERATED — do not edit by hand
// Source: design/brandbook/someai/tokens.json
// Generated by: design/compile-tokens.mjs

import 'package:charlotte_ui/theme.dart';
import 'package:flutter/material.dart';

/// SomeAI brand color palette
class SomeaiColors {
  SomeaiColors._();

  static const primary = ColorSwatch9(
    shade100: Color(0xFFFED7D7),
    shade200: Color(0xFFFEB2B2),
    shade300: Color(0xFFFC8181),
    shade400: Color(0xFFF56565),
    shade500: Color(0xFFE53E3E),
    shade600: Color(0xFFC53030),
    shade700: Color(0xFF9B2C2C),
    shade800: Color(0xFF7B2020),
    shade900: Color(0xFF5C1111),
  );

  static const secondary = ColorSwatch9(
    shade100: Color(0xFFE8D5D5),
    shade200: Color(0xFFD4BCBC),
    shade300: Color(0xFFC4A8A8),
    shade400: Color(0xFFAB9090),
    shade500: Color(0xFF9B7878),
    shade600: Color(0xFF876464),
    shade700: Color(0xFF6B4F4F),
    shade800: Color(0xFF503C3C),
    shade900: Color(0xFF382A2A),
  );

  static const tertiary = ColorSwatch9(
    shade100: Color(0xFFD4EEFC),
    shade200: Color(0xFFA8DBF8),
    shade300: Color(0xFF6EC2F0),
    shade400: Color(0xFF3BABE8),
    shade500: Color(0xFF1A94D5),
    shade600: Color(0xFF1478AB),
    shade700: Color(0xFF0F5C82),
    shade800: Color(0xFF0A4058),
    shade900: Color(0xFF06242F),
  );

  static const error = ColorSwatch9(
    shade100: Color(0xFFFED7D7),
    shade200: Color(0xFFFEB2B2),
    shade300: Color(0xFFFC8181),
    shade400: Color(0xFFF56565),
    shade500: Color(0xFFE53E3E),
    shade600: Color(0xFFC53030),
    shade700: Color(0xFF9B2C2C),
    shade800: Color(0xFF822727),
    shade900: Color(0xFF63171B),
  );

  static const background = Color(0xFF141414);
  static const surface = Color(0xFF1A1A1A);
  static const surfaceVariant = Color(0xFF222222);

  static const textPrimary = Color(0xFFE8E0E0);
  static const textTertiary = Color(0xFF666666);
}

/// SomeAI theme configuration
const someaiThemeConfig = CharlotteThemeConfig(
  primary: SomeaiColors.primary,
  secondary: SomeaiColors.secondary,
  tertiary: SomeaiColors.tertiary,
  error: SomeaiColors.error,
  background: SomeaiColors.background,
  surface: SomeaiColors.surface,
  surfaceVariant: SomeaiColors.surfaceVariant,
  textPrimary: SomeaiColors.textPrimary,
  textSecondary: SomeaiColors.textPrimary,
  textTertiary: SomeaiColors.textTertiary,
  textDisabled: Color(0xFF666666),
  glassBlurSubtle: 12,
  glassBlurStandard: 24,
  glassBlurFrosted: 40,
  glassBlurDeep: 60,
  glassFillOpacity: 0.15,
  glassBorderOpacity: 0.18,
  headingFontFamily: 'Inter',
  bodyFontFamily: 'Inter',
  radiusSmall: 10,
  radiusMedium: 16,
  radiusLarge: 22,
);
