// GENERATED — do not edit by hand
// Source: design/brandbook/richard-enterprises/tokens.json
// Generated by: design/compile-tokens.mjs

import 'package:charlotte_ui/theme.dart';
import 'package:flutter/material.dart';

/// RichardEnterprises brand color palette
class RichardEnterprisesColors {
  RichardEnterprisesColors._();

  static const primary = ColorSwatch9(
    shade100: Color(0xFFF5EACC),
    shade200: Color(0xFFEDD9A0),
    shade300: Color(0xFFE4C878),
    shade400: Color(0xFFD8B45C),
    shade500: Color(0xFFC8A040),
    shade600: Color(0xFFA88530),
    shade700: Color(0xFF987020),
    shade800: Color(0xFF7A5A18),
    shade900: Color(0xFF5C4410),
  );

  static const secondary = ColorSwatch9(
    shade100: Color(0xFFCDD5E8),
    shade200: Color(0xFFA0ADCC),
    shade300: Color(0xFF7085B0),
    shade400: Color(0xFF4D6894),
    shade500: Color(0xFF1A2B5F),
    shade600: Color(0xFF162550),
    shade700: Color(0xFF121E40),
    shade800: Color(0xFF0E1830),
    shade900: Color(0xFF0A1020),
  );

  static const tertiary = ColorSwatch9(
    shade100: Color(0xFFF0F0F2),
    shade200: Color(0xFFD8D8DC),
    shade300: Color(0xFFB0B0B8),
    shade400: Color(0xFF888890),
    shade500: Color(0xFF68686E),
    shade600: Color(0xFF505058),
    shade700: Color(0xFF3C3C42),
    shade800: Color(0xFF282830),
    shade900: Color(0xFF1C1C22),
  );

  static const error = ColorSwatch9(
    shade100: Color(0xFFFEE2E2),
    shade200: Color(0xFFFECACA),
    shade300: Color(0xFFFCA5A5),
    shade400: Color(0xFFF87171),
    shade500: Color(0xFFEF4444),
    shade600: Color(0xFFDC2626),
    shade700: Color(0xFFB91C1C),
    shade800: Color(0xFF991B1B),
    shade900: Color(0xFF7F1D1D),
  );

  static const background = Color(0xFF0C0C0E);
  static const surface = Color(0xFF141418);
  static const surfaceVariant = Color(0xFF1C1C22);

  static const textPrimary = Color(0xFFF0F0F2);
  static const textTertiary = Color(0xFF888890);
}

/// Richard Enterprises theme configuration
const richardEnterprisesThemeConfig = CharlotteThemeConfig(
  primary: RichardEnterprisesColors.primary,
  secondary: RichardEnterprisesColors.secondary,
  tertiary: RichardEnterprisesColors.tertiary,
  error: RichardEnterprisesColors.error,
  background: RichardEnterprisesColors.background,
  surface: RichardEnterprisesColors.surface,
  surfaceVariant: RichardEnterprisesColors.surfaceVariant,
  textPrimary: RichardEnterprisesColors.textPrimary,
  textSecondary: RichardEnterprisesColors.textPrimary,
  textTertiary: RichardEnterprisesColors.textTertiary,
  textDisabled: Color(0xFF888890),
  glassBlurSubtle: 12,
  glassBlurStandard: 24,
  glassBlurFrosted: 40,
  glassBlurDeep: 60,
  glassFillOpacity: 0.12,
  glassBorderOpacity: 0.16,
  headingFontFamily: 'Inter',
  bodyFontFamily: 'Inter',
  radiusSmall: 10,
  radiusMedium: 16,
  radiusLarge: 22,
);
