// GENERATED — do not edit by hand
// Source: design/brandbook/sounder/tokens.json
// Generated by: design/compile-tokens.mjs

import 'package:charlotte_ui/theme.dart';
import 'package:flutter/material.dart';

/// Sounder brand color palette
class SounderColors {
  SounderColors._();

  static const primary = ColorSwatch9(
    shade100: Color(0xFFE3CCF5),
    shade200: Color(0xFFC799EA),
    shade300: Color(0xFFAA66E0),
    shade400: Color(0xFF8E33D5),
    shade500: Color(0xFF7200CB),
    shade600: Color(0xFF5B00A2),
    shade700: Color(0xFF44007A),
    shade800: Color(0xFF2E0051),
    shade900: Color(0xFF170029),
  );

  static const secondary = ColorSwatch9(
    shade100: Color(0xFFFCCCF6),
    shade200: Color(0xFFF999ED),
    shade300: Color(0xFFF666E4),
    shade400: Color(0xFFF333DB),
    shade500: Color(0xFFF000D2),
    shade600: Color(0xFFC000A8),
    shade700: Color(0xFF90007E),
    shade800: Color(0xFF600054),
    shade900: Color(0xFF30002A),
  );

  static const tertiary = ColorSwatch9(
    shade100: Color(0xFFD3F7F4),
    shade200: Color(0xFFA6EFE8),
    shade300: Color(0xFF7AE6DD),
    shade400: Color(0xFF4DDED1),
    shade500: Color(0xFF21D6C6),
    shade600: Color(0xFF1AAB9E),
    shade700: Color(0xFF148077),
    shade800: Color(0xFF0D564F),
    shade900: Color(0xFF072B28),
  );

  static const error = ColorSwatch9(
    shade100: Color(0xFFF5DCDC),
    shade200: Color(0xFFEBB9B9),
    shade300: Color(0xFFE29597),
    shade400: Color(0xFFD87274),
    shade500: Color(0xFFCE4F51),
    shade600: Color(0xFFA53F41),
    shade700: Color(0xFF7C2F31),
    shade800: Color(0xFF522020),
    shade900: Color(0xFF291010),
  );

  static const background = Color(0xFF232324);
  static const surface = Color(0xFF2D2B2E);
  static const surfaceVariant = Color(0xFF3D3B3E);

  static const textPrimary = Color(0xFFF2F2F3);
  static const textTertiary = Color(0xFF5B575E);
}

/// Sounder theme configuration
const sounderGeneratedThemeConfig = CharlotteThemeConfig(
  primary: SounderColors.primary,
  secondary: SounderColors.secondary,
  tertiary: SounderColors.tertiary,
  error: SounderColors.error,
  background: SounderColors.background,
  surface: SounderColors.surface,
  surfaceVariant: SounderColors.surfaceVariant,
  textPrimary: SounderColors.textPrimary,
  textSecondary: SounderColors.textPrimary,
  textTertiary: SounderColors.textTertiary,
  textDisabled: Color(0xFF5B575E),
  glassBlurSubtle: 12,
  glassBlurStandard: 24,
  glassBlurFrosted: 40,
  glassBlurDeep: 60,
  glassFillOpacity: 0.10,
  glassBorderOpacity: 0.20,
  headingFontFamily: 'Oswald',
  bodyFontFamily: 'Inter',
  radiusSmall: 10,
  radiusMedium: 16,
  radiusLarge: 22,
);
