#!/usr/bin/env node
// compile-tokens.mjs — Reads a brand's tokens.json and emits:
//   1. <brand>_theme.dart  (CharlotteThemeConfig constant)
//   2. <brand>_theme.css   (CSS custom properties with --lg-* prefix)
//
// Usage:  node design/compile-tokens.mjs <brand>
//   e.g.  node design/compile-tokens.mjs someai
//         node design/compile-tokens.mjs richard-enterprises

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const brand = process.argv[2];

if (!brand) {
  console.error('Usage: node design/compile-tokens.mjs <brand>');
  console.error('Brands: someai, isg, sea-lion, sounder, richard-enterprises');
  process.exit(1);
}

const brandDir = join(__dirname, 'brandbook', brand);
const tokensPath = join(brandDir, 'tokens.json');

let tokens;
try {
  tokens = JSON.parse(readFileSync(tokensPath, 'utf-8'));
} catch (e) {
  console.error(`Failed to read ${tokensPath}: ${e.message}`);
  process.exit(1);
}

const theme = tokens.theme;
if (!theme) {
  console.error(`No "theme" key found in ${tokensPath}`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert brand slug to PascalCase: "richard-enterprises" → "RichardEnterprises" */
function pascalCase(s) {
  return s.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join('');
}

/** Convert brand slug to camelCase: "richard-enterprises" → "richardEnterprises" */
function camelCase(s) {
  const parts = s.split('-');
  return parts[0] + parts.slice(1).map(w => w[0].toUpperCase() + w.slice(1)).join('');
}

/** Hex string "#E53E3E" → "0xFFE53E3E" */
function hexToDartColor(hex) {
  const h = hex.replace('#', '').toUpperCase();
  return `Color(0xFF${h})`;
}

/** Shades object → list of [step, hex] sorted by step */
function sortedShades(ramp) {
  return Object.entries(ramp)
    .map(([k, v]) => [parseInt(k), v])
    .sort((a, b) => a[0] - b[0]);
}

// ---------------------------------------------------------------------------
// Output A — Dart theme config
// ---------------------------------------------------------------------------

function emitDart() {
  const pc = pascalCase(brand);
  const cc = camelCase(brand);
  const g = theme.glass || {};
  const r = theme.radius || {};
  const f = theme.font || {};

  function swatchLiteral(name, ramp) {
    const shades = sortedShades(ramp);
    // ColorSwatch9 uses 100-900
    const s = {};
    for (const [step, hex] of shades) {
      if (step >= 100 && step <= 900) s[step] = hex;
    }
    const lines = [];
    for (let i = 100; i <= 900; i += 100) {
      const hex = s[i];
      if (!hex) continue;
      lines.push(`    shade${i}: ${hexToDartColor(hex)},`);
    }
    return `  static const ${name} = ColorSwatch9(\n${lines.join('\n')}\n  );`;
  }

  const lines = [
    "// GENERATED — do not edit by hand",
    `// Source: design/brandbook/${brand}/tokens.json`,
    `// Generated by: design/compile-tokens.mjs`,
    "",
    "import 'package:charlotte_ui/theme.dart';",
    "import 'package:flutter/material.dart';",
    "",
    `/// ${pc} brand color palette`,
    `class ${pc}Colors {`,
    `  ${pc}Colors._();`,
    "",
    swatchLiteral('primary', theme.primary),
    "",
    swatchLiteral('secondary', theme.secondary),
    "",
    swatchLiteral('tertiary', theme.tertiary),
    "",
    swatchLiteral('error', theme.error),
    "",
    `  static const background = ${hexToDartColor(theme.background)};`,
    `  static const surface = ${hexToDartColor(theme.surface)};`,
    `  static const surfaceVariant = ${hexToDartColor(theme.surfaceVariant)};`,
    "",
    `  static const textPrimary = ${hexToDartColor(theme.text)};`,
    `  static const textSecondary = ${hexToDartColor(theme.text)}.withValues(alpha: 0.7);`,
    `  static const textTertiary = ${hexToDartColor(theme.textDim)};`,
    `  static const textDisabled = ${hexToDartColor(theme.textDim)}.withValues(alpha: 0.6);`,
    "}",
    "",
    `/// ${pc} theme configuration`,
    `const ${cc}ThemeConfig = CharlotteThemeConfig(`,
    `  primary: ${pc}Colors.primary,`,
    `  secondary: ${pc}Colors.secondary,`,
    `  tertiary: ${pc}Colors.tertiary,`,
    `  error: ${pc}Colors.error,`,
    `  background: ${pc}Colors.background,`,
    `  surface: ${pc}Colors.surface,`,
    `  surfaceVariant: ${pc}Colors.surfaceVariant,`,
    `  textPrimary: ${pc}Colors.textPrimary,`,
    `  textSecondary: ${pc}Colors.textPrimary,`,
    `  textTertiary: ${pc}Colors.textTertiary,`,
    `  textDisabled: ${pc}Colors.textDisabled,`,
    `  glassBlurSubtle: ${g.blurSubtle ?? 12},`,
    `  glassBlurStandard: ${g.blurStandard ?? 24},`,
    `  glassBlurFrosted: ${g.blurFrosted ?? 40},`,
    `  glassBlurDeep: ${g.blurDeep ?? 60},`,
    `  glassFillOpacity: ${g.fillOpacity ?? 0.15},`,
    `  glassBorderOpacity: ${g.borderOpacity ?? 0.18},`,
    `  headingFontFamily: '${f.heading ?? 'Inter'}',`,
    `  bodyFontFamily: '${f.body ?? 'Inter'}',`,
    `  radiusSmall: ${r.sm ?? 10},`,
    `  radiusMedium: ${r.md ?? 16},`,
    `  radiusLarge: ${r.lg ?? 22},`,
    ");",
    "",
  ];

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Output B — CSS custom properties
// ---------------------------------------------------------------------------

function emitCSS() {
  const g = theme.glass || {};
  const r = theme.radius || {};
  const f = theme.font || {};
  const lines = [
    `/* GENERATED — do not edit by hand */`,
    `/* Source: design/brandbook/${brand}/tokens.json */`,
    `/* Generated by: design/compile-tokens.mjs */`,
    "",
    ":root {",
  ];

  // Color ramps
  for (const rampName of ['primary', 'secondary', 'tertiary', 'error', 'neutral']) {
    const ramp = theme[rampName];
    if (!ramp) continue;
    for (const [step, hex] of sortedShades(ramp)) {
      lines.push(`  --lg-${rampName}-${step}: ${hex};`);
    }
  }

  // Surface / text
  lines.push("");
  lines.push(`  --lg-bg: ${theme.background};`);
  lines.push(`  --lg-surface: ${theme.surface};`);
  lines.push(`  --lg-surface-variant: ${theme.surfaceVariant};`);
  lines.push(`  --lg-border: ${theme.border};`);
  lines.push(`  --lg-text: ${theme.text};`);
  lines.push(`  --lg-text-dim: ${theme.textDim};`);

  // Glass
  lines.push("");
  lines.push(`  --lg-blur-subtle: ${g.blurSubtle ?? 12}px;`);
  lines.push(`  --lg-blur-standard: ${g.blurStandard ?? 24}px;`);
  lines.push(`  --lg-blur-frosted: ${g.blurFrosted ?? 40}px;`);
  lines.push(`  --lg-blur-deep: ${g.blurDeep ?? 60}px;`);
  lines.push(`  --lg-fill-opacity: ${g.fillOpacity ?? 0.15};`);
  lines.push(`  --lg-border-opacity: ${g.borderOpacity ?? 0.18};`);
  lines.push(`  --lg-saturation: ${g.saturation ?? 180}%;`);

  // Radius
  lines.push("");
  lines.push(`  --lg-radius-sm: ${r.sm ?? 10}px;`);
  lines.push(`  --lg-radius-md: ${r.md ?? 16}px;`);
  lines.push(`  --lg-radius-lg: ${r.lg ?? 22}px;`);

  // Typography
  lines.push("");
  lines.push(`  --lg-font-heading: ${f.heading ?? 'Inter'}, -apple-system, sans-serif;`);
  lines.push(`  --lg-font-body: ${f.body ?? 'Inter'}, -apple-system, sans-serif;`);
  lines.push(`  --lg-font-mono: ${f.mono ?? 'SF Mono, Cascadia Code, monospace'};`);

  lines.push("}");
  lines.push("");

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Write outputs
// ---------------------------------------------------------------------------

const slug = brand; // e.g. "someai", "richard-enterprises"
const dartFile = join(brandDir, `${slug.replace(/-/g, '_')}_theme.dart`);
const cssFile = join(brandDir, `${slug.replace(/-/g, '_')}_theme.css`);

writeFileSync(dartFile, emitDart(), 'utf-8');
console.log(`✓ ${dartFile}`);

writeFileSync(cssFile, emitCSS(), 'utf-8');
console.log(`✓ ${cssFile}`);
