// GENERATED — do not edit by hand
// Source: design/brandbook/isg/tokens.json
// Generated by: design/compile-tokens.mjs

import 'package:charlotte_ui/theme.dart';
import 'package:flutter/material.dart';

/// ISG brand color palette
class IsgColors {
  IsgColors._();

  static const primary = ColorSwatch9(
    shade100: Color(0xFFD6E2F3),
    shade200: Color(0xFFB8CCE9),
    shade300: Color(0xFF9AB6DF),
    shade400: Color(0xFF8FAADC),
    shade500: Color(0xFF7094CC),
    shade600: Color(0xFF5478B0),
    shade700: Color(0xFF3D5F94),
    shade800: Color(0xFF2A4570),
    shade900: Color(0xFF162B4D),
  );

  static const secondary = ColorSwatch9(
    shade100: Color(0xFFF9E8C4),
    shade200: Color(0xFFF4D89C),
    shade300: Color(0xFFF0C86A),
    shade400: Color(0xFFE8B44E),
    shade500: Color(0xFFE2A532),
    shade600: Color(0xFFC88E24),
    shade700: Color(0xFFB8841E),
    shade800: Color(0xFF8E6616),
    shade900: Color(0xFF64480E),
  );

  static const tertiary = ColorSwatch9(
    shade100: Color(0xFFCCFBF8),
    shade200: Color(0xFF99F6F0),
    shade300: Color(0xFF5CEEE4),
    shade400: Color(0xFF22D3EE),
    shade500: Color(0xFF06B6D4),
    shade600: Color(0xFF0891B2),
    shade700: Color(0xFF0E7490),
    shade800: Color(0xFF155E75),
    shade900: Color(0xFF164E63),
  );

  static const error = ColorSwatch9(
    shade100: Color(0xFFFEE2E2),
    shade200: Color(0xFFFECACA),
    shade300: Color(0xFFFCA5A5),
    shade400: Color(0xFFF87171),
    shade500: Color(0xFFEF4444),
    shade600: Color(0xFFDC2626),
    shade700: Color(0xFFB91C1C),
    shade800: Color(0xFF991B1B),
    shade900: Color(0xFF7F1D1D),
  );

  static const background = Color(0xFF0A1628);
  static const surface = Color(0xFF0F1D36);
  static const surfaceVariant = Color(0xFF1A2B5F);

  static const textPrimary = Color(0xFFE2E8F0);
  static const textTertiary = Color(0xFF94A3B8);
}

/// ISG theme configuration
const isgThemeConfig = CharlotteThemeConfig(
  primary: IsgColors.primary,
  secondary: IsgColors.secondary,
  tertiary: IsgColors.tertiary,
  error: IsgColors.error,
  background: IsgColors.background,
  surface: IsgColors.surface,
  surfaceVariant: IsgColors.surfaceVariant,
  textPrimary: IsgColors.textPrimary,
  textSecondary: IsgColors.textPrimary,
  textTertiary: IsgColors.textTertiary,
  textDisabled: Color(0xFF94A3B8),
  glassBlurSubtle: 12,
  glassBlurStandard: 24,
  glassBlurFrosted: 40,
  glassBlurDeep: 60,
  glassFillOpacity: 0.12,
  glassBorderOpacity: 0.15,
  headingFontFamily: 'Inter',
  bodyFontFamily: 'Inter',
  radiusSmall: 10,
  radiusMedium: 16,
  radiusLarge: 22,
);
