// GENERATED — do not edit by hand
// Source: design/brandbook/sea-lion/tokens.json
// Generated by: design/compile-tokens.mjs

import 'package:charlotte_ui/theme.dart';
import 'package:flutter/material.dart';

/// SeaLion brand color palette
class SeaLionColors {
  SeaLionColors._();

  static const primary = ColorSwatch9(
    shade100: Color(0xFFDBEAFE),
    shade200: Color(0xFFBFDBFE),
    shade300: Color(0xFF93C5FD),
    shade400: Color(0xFF60A5FA),
    shade500: Color(0xFF3B82F6),
    shade600: Color(0xFF2563EB),
    shade700: Color(0xFF1D4ED8),
    shade800: Color(0xFF1E3A5F),
    shade900: Color(0xFF0A1628),
  );

  static const secondary = ColorSwatch9(
    shade100: Color(0xFFFEF3C7),
    shade200: Color(0xFFFDE68A),
    shade300: Color(0xFFFCD34D),
    shade400: Color(0xFFFBBF24),
    shade500: Color(0xFFF59E0B),
    shade600: Color(0xFFD97706),
    shade700: Color(0xFFB45309),
    shade800: Color(0xFF92400E),
    shade900: Color(0xFF78350F),
  );

  static const tertiary = ColorSwatch9(
    shade100: Color(0xFFCFFAFE),
    shade200: Color(0xFFA5F3FC),
    shade300: Color(0xFF67E8F9),
    shade400: Color(0xFF22D3EE),
    shade500: Color(0xFF06B6D4),
    shade600: Color(0xFF0891B2),
    shade700: Color(0xFF0E7490),
    shade800: Color(0xFF155E75),
    shade900: Color(0xFF164E63),
  );

  static const error = ColorSwatch9(
    shade100: Color(0xFFFEE2E2),
    shade200: Color(0xFFFECACA),
    shade300: Color(0xFFFCA5A5),
    shade400: Color(0xFFF87171),
    shade500: Color(0xFFEF4444),
    shade600: Color(0xFFDC2626),
    shade700: Color(0xFFB91C1C),
    shade800: Color(0xFF991B1B),
    shade900: Color(0xFF7F1D1D),
  );

  static const background = Color(0xFF0A1628);
  static const surface = Color(0xFF0F1D36);
  static const surfaceVariant = Color(0xFF1A2B5F);

  static const textPrimary = Color(0xFFE2E8F0);
  static const textTertiary = Color(0xFF94A3B8);
}

/// Sea Lion theme configuration
const seaLionThemeConfig = CharlotteThemeConfig(
  primary: SeaLionColors.primary,
  secondary: SeaLionColors.secondary,
  tertiary: SeaLionColors.tertiary,
  error: SeaLionColors.error,
  background: SeaLionColors.background,
  surface: SeaLionColors.surface,
  surfaceVariant: SeaLionColors.surfaceVariant,
  textPrimary: SeaLionColors.textPrimary,
  textSecondary: SeaLionColors.textPrimary,
  textTertiary: SeaLionColors.textTertiary,
  textDisabled: Color(0xFF94A3B8),
  glassBlurSubtle: 12,
  glassBlurStandard: 24,
  glassBlurFrosted: 40,
  glassBlurDeep: 60,
  glassFillOpacity: 0.15,
  glassBorderOpacity: 0.18,
  headingFontFamily: 'Inter',
  bodyFontFamily: 'Inter',
  radiusSmall: 10,
  radiusMedium: 16,
  radiusLarge: 22,
);
